version: "3.8"
services:
  app-banco:
    build: .
    depends_on:
      - bdd-mysql
    ports:
      - "3000:3000"
    environment: 
      - password=root
      - user=root
      - host=bdd-mysql
    links:
      - bdd-mysql
    container_name: app-banco
  bdd-mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=blas
      - MYSQL_PASSWORD=password     
    container_name: mysql-bdd
    volumes: 
      - ./bd_mysql/bancoall.sql:/docker-entrypoint-initdb.d/bancoall.sql
volumes:
  dumps:


  

 

